### @name="GET ALL PRODUCTS"
GET http://localhost:8080/api/products
Accept:application/json


### @name="GET PRODUCTS BY RANGE"
GET http://localhost:8080/api/products?low=50000&high=200000
Accept:application/json


### @name="GET PRODUCT BY ID"
GET http://localhost:8080/api/products/2
Accept:application/json

### @name="GET PRODUCT HATEOAS BY ID"
GET http://localhost:8080/api/products/hateos/2
Accept:application/json

### @name="ADD PRODUCT"
POST http://localhost:8080/api/products
Accept:application/json
Content-Type:application/json


{
  "name": "Samsung OLED",
  "price": 154000.00,
  "quantity": 100
}

### @name="ADD INVALID PRODUCT"
POST http://localhost:8080/api/products
Accept:application/json
Content-Type:application/json
Accept-Language: fr

{
  "name": "",
  "price": 0,
  "quantity": -100
}

### @name="UPDATE PRODUCT"
PATCH http://localhost:8080/api/products/1?price=7777.00
Accept:application/json
Content-Type:application/json